export const items = [
  {
    id: 0,
    image: "/image/one.png",
    startDate: "2024-10-10",
    endDate: "2024-10-30",
    type: "Easy",
    title: "Data Science Bootcamp - Graded Datathon",
    description: "Identify butterfly species based on their characteristics and data points.",
  },
  {
    id: 1,
    image: "/image/two.png",
    startDate: "2024-08-29",
    endDate: "2024-11-02",
    type: "Hard",
    title: "Data Sprint 70 - Airline Passenger Satisfaction",
    description: "Predict passenger satisfaction using airline service data and metrics.",
  },
  {
    id: 2,
    image: "/image/three.png",
    startDate: "2024-10-01",
    endDate: "2024-12-30",
    type: "Medium",
    title: "Data Sprint 72 - Butterfly Identification",
    description: "Classify butterflies into their respective species using provided datasets.",
  },
  {
    id: 3,
    image: "/image/four.png",
    startDate: "2024-07-01",
    endDate: "2024-07-30",
    type: "Easy",
    title: "Engineering Graduates Employment Outcomes",
    description: "Analyze factors influencing employment outcomes of engineering graduates.",
  },
  {
    id: 4,
    image: "/image/five.png",
    startDate: "2024-08-20",
    endDate: "2024-10-30",
    type: "Medium",
    title: "Data Sprint 71 - Weather Recognition",
    description: "Develop models to recognize weather patterns based on historical data.",
  },
  {
    id: 5,
    image: "/image/six.png",
    startDate: "2023-06-18",
    endDate: "2024-06-30",
    type: "Easy",
    title: "Travel Insurance Claim Prediction",
    description: "Predict claims for travel insurance based on user profiles and claims history.",
  },
];
